<footer>
    <p>&copy; Solvex: We Specialize in Your Solutions</p>
    <p>Github Repository: <a href="https://github.com/Janet1411/project1.git" target="_blank" title="Git-Repo">g03 - Solvex</a></p>
    <p>Jira: <a href="https://khubi021006.atlassian.net/jira/software/projects/SCRUM/boards/1/backlog?epics=visible&atlOrigin=eyJpIjoiMDZkMGUzZjI4NTQwNDAxNGExOTY2Njk3MjAwMmVjNTUiLCJwIjoiaiJ9" target="_blank" title="Jira">g03 - Solvex</a></p>
    <!-- git live link: https://janet1411.github.io/project1/-->
    <a href="enhancements.php">Enchancements</a>
</footer>